name: hela
epochs: 200
augment: 5
batchsize: 152
size: 96
cam_size: 960
backbone: unet
features: 32
train_samples_per_epoch: 50000
num_workers: 4
projhead: minimal_batchnorm
classhead: minimal
input_train:
- data/hela/train/01
- data/hela/train/02
- data/hela/test/01
- data/hela/test/02
split_train:
- - 0.1
  - 1.0
split_val:
- 0.0
- 0.1
